"""create core schema: users, forms, form_versions, fields, field_options, conditional_rules, submissions, response_values

Revision ID: 36750f78ed6c
Revises: 
Create Date: 2026-08-26 13:52:40.697764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36750f78ed6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'version_number', name='uq_form_versions_form_id_version_number')
    )
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_version_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('validation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_form_version_id'), 'fields', ['form_version_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_version_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completion_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_form_version_id'), 'submissions', ['form_version_id'], unique=False)
    op.create_table('conditional_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_field_id', sa.UUID(), nullable=False),
    sa.Column('target_field_id', sa.UUID(), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('comparison_value', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['target_field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('option_label', sa.String(length=255), nullable=False),
    sa.Column('option_value', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_options_field_id'), 'field_options', ['field_id'], unique=False)
    op.create_table('response_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_values_field_id'), 'response_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_response_values_submission_id'), 'response_values', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_values_submission_id'), table_name='response_values')
    op.drop_index(op.f('ix_response_values_field_id'), table_name='response_values')
    op.drop_table('response_values')
    op.drop_index(op.f('ix_field_options_field_id'), table_name='field_options')
    op.drop_table('field_options')
    op.drop_table('conditional_rules')
    op.drop_index(op.f('ix_submissions_form_version_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_fields_form_version_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_table('form_versions')
    op.drop_table('forms')
    op.drop_table('users')
    # ### end Alembic commands ###
